### ISSUE TITLE
Client sollten per default JSON bekommen

### ISSUE THREAD

**Issue by lu-j** [OParl/php-server#1]
Aktuell müssen Clients entweder den `accept: application/json` Header mitschicken oder `?format=json` an jede URL anhängen.
Das default Format sollte JSON sein. Mit `?format=html` sollte man die HTML Ausgabe aktivieren können. In der HTML Ausgabe sollte der Server dann an alle URLs automatisch `?format=html` anhängen, damit man weiterhin bequem auf die URLs klicken kann und wieder die HTML Ausgabe bekommt.

**Comment by akuckartz** [comment]
Mit REST hat das allerdings nicht viel zu tun.

**Comment by eFrane** [comment]
1. Ist REST sehr dehnbar. Es gibt zwar die eine oder andere Richtlinie, an die sich alle halten, aber im großen und ganzen ist doch jede API ihr eigene kleine Experimentierwiese. 
2. Ist aber der `accept`-Header etwas, was mir in den letzten Jahren immer häufiger als Methode der Ausgabeformatswahl begegnet ist. Daher würde ich den schon gerne beibehalten.
3. HTML nicht als Standardausgabeformat zu wählen ist vielleicht nicht die schlechteste Idee für diese Implementation, hat aber imho nichts mit Konformanz zur Spezifikation oder irgendeiner Definition von REST zu tun.
